version: 2
builds:
  - main: ./cmd/rvglsm
    binary: rvglsm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
upx:
  - enabled: true
    goos:
      - linux
      - windows
release:
  prerelease: auto
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
archives:
  - format_overrides:
    - goos: windows
      formats: zip
homebrew_casks:
  - repository:
      owner: frantjc
      name: homebrew-tap
    name: rvglsm
    conflicts:
      - formula: rvglsm
    hooks:
      post:
        install: |
          if OS.mac?
            if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/rvglsm"]
            end
          end
