version: 2
builds:
  - main: ./cmd/rvglsm
    binary: rvglsm
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    hooks:
      post:
        - upx {{ .Path }}
release:
  prerelease: auto
changelog:
  use: github
  filters:
    exclude:
      - merge conflict
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
brews:
  - repository:
      owner: frantjc
      name: homebrew-tap
    name: rvglsm
    directory: Formula
    skip_upload: auto
    homepage:  https://github.com/frantjc/rvgl-utils
    license: MIT
    install: |
      bin.install "rvglsm"
    test: |
      system "#{bin}/rvglsm --version"
